version: "3"
services: 
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=Root
      - MONGO_PASSWORD=123456
      - SESSION_SECRET=secret
    command: npm run start
  mongo: 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=Root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  

